language: python
matrix:
  include:
    - python: 3.7
      env: TOXENV=py37
    - python: 3.8
      env: TOXENV=py38
    - python: 3.9
      env: TOXENV=py39
    - python: pypy3
      env: TOXENV=pypy3
    - python: 3.9
      env: TOXENV=flake8
# command to install dependencies
install:
  - "pip install -U pip setuptools"
  - "pip install tox"

# command to run tests
script: tox
